// <auto-generated />
namespace Bll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddingTense : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingTense));
        
        string IMigrationMetadata.Id
        {
            get { return "201406291234173_AddingTense"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
